#!/bin/bash

function count_jobs() {
  i=`ps -ef |grep "recording_finished" |grep -v grep|wc -l`
  echo $i
}

UPLOADING_JOBS=`count_jobs`

while [ $UPLOADING_JOBS -ne 0 ]
do
  case $UPLOADING_JOBS in
    1) echo "UPLOADING_JOBS is $UPLOADING_JOBS. Wait till other jobs complete."
       sleep 10
       UPLOADING_JOBS=`count_jobs`
       ;;
    *) echo "UPLOADING_JOBS is $UPLOADING_JOBS. Many jobs in queue, aborting."
       exit 0
       ;;
  esac
done

echo "Start uploading"
sleep 30
#/bin/bash -l -c '/root/dropbox_uploader.sh upload /root/Music/Radiko/*.mp3  /'

echo "Deleting linode"
#/bin/bash -l -c 'linode delete ripdiko'
