#  install ruby
#  https://gist.githubusercontent.com/owainlewis/7098068/
## ===============================================
- hosts: all
  vars:
      repo: https://github.com/harupong/ripdiko.git
      target: ~/ripdiko

  tasks:
  - name: Install Ruby
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - ruby2.0
      - ruby2.0-dev

  - name: apt install dependencies for ruby2.0
    command: "sudo apt-get -y build-dep ruby2.0"

  - name: remove ruby1.9.3
    apt: name=ruby1.9.1 state=absent

  - name: install required gems
    gem: name={{item}} state=present user_install=no
    with_items:
      - bundler

  - name: apt install dependencies for ripdiko and linode-cli
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - git
      - libxml2-dev
      - libxslt1-dev
      - rtmpdump
      - swftools
      - libavcodec-extra-53
      - python-pycurl       #linode-cli

  - name: add linode-cli apt repo
    apt_repository: repo='deb http://apt.linode.com/ stable main' state=present update_cache=yes

  - name: add linode-cli apt repo key
    apt_key: url=https://apt.linode.com/linode.gpg state=present

  - name: apt install linode-cli
    apt: name={{item}} state=present update_cache=yes
    with_items:
      - linode-cli

  - name: Clone ripdiko from github
    git: repo={{repo}} dest={{ target }}

  - name: Installing gem dependencies for ripdiko
    command: "bundle install chdir={{target}}"

    # ~/bin/ffmpeg was downloaded from http://ffmpeg.gusari.org/static/
  - name: Install ffmpeg
    copy: src=~/bin/ffmpeg dest=/usr/bin/ffmpeg owner=root group=root mode=0754

  - name: Install Dropbox-uploader
    copy: src=~/ansible-funbook/dropbox_uploader.sh dest=/root/dropbox_uploader.sh owner=root group=root mode=0754

  - name: Copy Dropbox-uploader config file
    copy: src=~/.dropbox_uploader dest=/root/.dropbox_uploader owner=root group=root mode=0644

  - name: Set timezone variables
    copy: content='Asia/Tokyo'
          dest=/etc/timezone
          owner=root
          group=root
          mode=0644
          backup=yes

  - name: update timezone
    command: dpkg-reconfigure --frontend noninteractive tzdata

  - name: restart cron service to reflect timezone change
    service: name=cron state=restarted

  - name: Copy recording_setupper.sh
    copy: src=~/ansible-funbook/recording_setupper.sh dest=/root/recording_setupper.sh owner=root group=root  mode=0777

  - name: Copy recording_controller.sh
    copy: src=~/ansible-funbook/recording_controller.sh dest=/root/recording_controller.sh owner=root group=root  mode=0777

  - name: mkdir linodecli
    file: dest=/root/.linodecli state=directory

  - name: copy linode-cli config
    copy: src=~/.linodecli/config dest=/root/.linodecli/config owner=root group=root  mode=0700

  - name: Creates cron entry for obtaining radiko authkey for recording JUNK/ANN
    cron: name="Obtain authkey" hour="0" minute="50" job="/bin/bash -l -c \"/root/recording_setupper.sh {{item}}\""
    with_items:
      - "TBS LFR"

  - name: Creates cron entry for ripdiko recording JUNK/ANN
    cron: name="Record" hour="1" minute="0" job="/bin/bash -l -c \"/root/recording_controller.sh {{item}}\""
    with_items:
      - "TBS LFR"

